[project]
name = "ppo-brax-ant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brax>=0.12.4",
    "flax>=0.10.7",
    "jax[cuda12]>=0.7.0",
    "mujoco-mjx>=3.3.4",
    "playground>=0.0.5",
    "wandb>=0.21.0",
]
